// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package models

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ColumnKey struct {
	_tab flatbuffers.Struct
}

func (rcv *ColumnKey) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ColumnKey) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ColumnKey) SeriesId() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *ColumnKey) MutateSeriesId(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *ColumnKey) FieldId() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *ColumnKey) MutateFieldId(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateColumnKey(builder *flatbuffers.Builder, seriesId uint64, fieldId uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependUint64(fieldId)
	builder.PrependUint64(seriesId)
	return builder.Offset()
}
