// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package models

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ColumnKeys struct {
	_tab flatbuffers.Table
}

func GetRootAsColumnKeys(buf []byte, offset flatbuffers.UOffsetT) *ColumnKeys {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ColumnKeys{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsColumnKeys(buf []byte, offset flatbuffers.UOffsetT) *ColumnKeys {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ColumnKeys{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ColumnKeys) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ColumnKeys) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ColumnKeys) ColumnKeys(obj *ColumnKey, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 16
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ColumnKeys) ColumnKeysLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ColumnKeysStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ColumnKeysAddColumnKeys(builder *flatbuffers.Builder, columnKeys flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(columnKeys), 0)
}
func ColumnKeysStartColumnKeysVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(16, numElems, 8)
}
func ColumnKeysEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
