// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package models

import "strconv"

type FieldType int32

const (
	FieldTypeUnknown  FieldType = -1
	FieldTypeFloat    FieldType = 0
	FieldTypeInteger  FieldType = 1
	FieldTypeUnsigned FieldType = 2
	FieldTypeBoolean  FieldType = 3
	FieldTypeString   FieldType = 4
)

var EnumNamesFieldType = map[FieldType]string{
	FieldTypeUnknown:  "Unknown",
	FieldTypeFloat:    "Float",
	FieldTypeInteger:  "Integer",
	FieldTypeUnsigned: "Unsigned",
	FieldTypeBoolean:  "Boolean",
	FieldTypeString:   "String",
}

var EnumValuesFieldType = map[string]FieldType{
	"Unknown":  FieldTypeUnknown,
	"Float":    FieldTypeFloat,
	"Integer":  FieldTypeInteger,
	"Unsigned": FieldTypeUnsigned,
	"Boolean":  FieldTypeBoolean,
	"String":   FieldTypeString,
}

func (v FieldType) String() string {
	if s, ok := EnumNamesFieldType[v]; ok {
		return s
	}
	return "FieldType(" + strconv.FormatInt(int64(v), 10) + ")"
}
