// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package models

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RowKey struct {
	_tab flatbuffers.Struct
}

func (rcv *RowKey) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RowKey) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *RowKey) SeriesId() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *RowKey) MutateSeriesId(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *RowKey) Timestamp() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *RowKey) MutateTimestamp(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateRowKey(builder *flatbuffers.Builder, seriesId uint64, timestamp uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependUint64(timestamp)
	builder.PrependUint64(seriesId)
	return builder.Offset()
}
